apiVersion: v1
kind: Service
metadata:
  name: test-workflow
  namespace: test-workflow-ns
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: test-workflow
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8080
